spring.application.name=spring-boot-learning
#spring.banner.location=my-banner.txt

spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mySecretKey
jwt.expiration=3600

spring.security.filter-dispatcher-types=async,forward,error,request
spring.security.filter-order=-100
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090

spring.security.csrf.enabled=false

spring.security.oauth2.resourceserver.jwt. can access / employee
